image: nikolaik/python-nodejs

pipelines:
  branches:
    staging:
        - step:
            caches:
              - node
            script: # Modify the commands below to build your repository.
              - apt-get update && apt-get install -y rsync
              - unset CI
              - npm install
              - npm rebuild node-sass
              - npm run build
              - rsync -r -v -e ssh ./build/ ubuntu@3.66.13.135:/var/www/subdomains/dashboardstaging --delete-before --exclude '.git'
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y rsync
            - unset CI
            - npm install
ate && apt-get install -y rsync
          - unset CI
          - npm install
          - npm run build
          - rsync -r -v -e ssh ./build/ ubuntu@3.66.13.135:/var/www/subdomains/dashboard2 --delete-before --exclude '.git' --exclude '.htaccess'